name: worldcountriesquiz
description: A World Countries Quiz Android Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  percent_indicator: ^3.0.1
  flutter_svg: ^0.22.0
  path_provider: ^2.0.2
  audioplayers: ^0.19.1
  google_mobile_ads: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/data/countries.json


    # Audio
    - assets/audio/wrong_answer.mp3
    - assets/audio/correct_answer.mp3
    - assets/audio/win.mp3


    # Images
    - assets/hint.png
    - assets/crown.png
    - assets/world.png
    - assets/Greece.png


    # SVG
    - assets/star.svg
    - assets/person_empty.svg
    - assets/person_full.svg
    - assets/devil.svg


    # Countries
    - assets/countries/Africa/Egypt.png

    - assets/countries/Asia/Pakistan.png

    - assets/countries/Europe/Greece.png
    - assets/countries/Europe/Italy.png

    - assets/countries/South America/Argentina.png


    # Shapes  
    - assets/shapes/Africa/Egypt.png

    - assets/shapes/Asia/Pakistan.png

    - assets/shapes/Europe/Greece.png
    - assets/shapes/Europe/Italy.png

    - assets/shapes/South America/Argentina.png


    # Flags
    - assets/flags/Africa/Egypt.png

    - assets/flags/Asia/Pakistan.png

    - assets/flags/Europe/Greece.png
    - assets/flags/Europe/Italy.png

    - assets/flags/South America/Argentina.png

    # Markers
    - assets/markers/Black.svg
    - assets/markers/Blue.svg
    - assets/markers/Green.svg
    - assets/markers/Red.svg
    - assets/markers/White.svg
    - assets/markers/Yellow.svg

    # Continents
    - assets/continents/Africa.png
    - assets/continents/Asia.png
    - assets/continents/Europe.png
    - assets/continents/North America.png
    - assets/continents/Oceania.png
    - assets/continents/South America.png